import type { Metadata } from "next";

export const siteMetadata: Metadata = {
  title: {
    default: "The Oakworth Group | Financial Modeling & Private Equity Advisory",
    template: "%s | The Oakworth Group"
  },
  description: "The Oakworth Group provides expert financial modeling, LBO analysis, debt structuring, and investment advisory services for private equity firms and corporations. Specializing in leveraged buyout modeling, capital structure optimization, and strategic financial analysis.",
  keywords: [
    "financial modeling", "private equity", "leveraged buyout", "LBO modeling", "investment analysis", 
    "capital structure", "debt structuring", "financial advisory", "corporate finance", "equity valuation",
    "IRR analysis", "MOIC calculation", "investment committee", "due diligence", "financial projections",
    "cash flow modeling", "valuation analysis", "DCF modeling", "comparable company analysis", 
    "transaction advisory", "merger and acquisition", "M&A advisory", "buyout analysis", "portfolio company",
    "financial restructuring", "debt capacity", "leverage analysis", "scenario planning", "sensitivity analysis",
    "equity waterfall", "investment returns", "risk assessment", "capital allocation", "performance benchmarking",
    "financial consulting", "strategic analysis", "executive summary", "investment memorandum", 
    "board presentation", "financial reporting", "tax aware modeling", "exit scenario analysis", 
    "refinancing advisory", "recapitalization", "covenant analysis", "lender presentation", "financial covenant",
    "debt financing", "multi-tranche debt", "leveraged finance", "financial services", "investment banking", 
    "corporate advisory", "financial expertise", "quantitative analysis", "data driven insights", 
    "financial decision making", "strategic investment", "capital markets", "financial engineering", 
    "structured finance", "financial solutions", "business valuation", "enterprise valuation", "asset valuation",
    "investment strategy", "portfolio management", "wealth management", "financial planning", "risk management",
    "financial risk", "market analysis", "industry analysis", "competitive analysis", "financial due diligence",
    "operational due diligence", "legal due diligence", "commercial due diligence", "technical due diligence", 
    "financial modeling firm", "private equity modeling", "corporate financial modeling", "investment banking modeling", 
    "financial analysis services", "financial consulting firm", "expert financial advice", "certified financial analysts", 
    "financial modeling experts", "private equity advisory", "corporate finance advisory", "investment advisory services", 
    "financial strategy consulting", "financial modeling training", "financial model development", "complex financial modeling", 
    "advanced financial modeling", "financial modeling software", "financial modeling tools", "financial modeling best practices", 
    "financial modeling standards", "financial modeling methodology", "financial modeling framework", "financial modeling process", 
    "financial modeling techniques", "financial modeling approaches", "financial modeling solutions", "financial modeling support", 
    "financial modeling assistance", "financial modeling guidance", "financial modeling expertise", "Oakworth Group", 
    "Oakworth financial", "Oakworth advisory", "Oakworth modeling", "Oakworth analysis", "Oakworth services", 
    "Oakworth consulting", "Oakworth expertise", "Oakworth solutions", "Oakworth professionals", "Oakworth team", 
    "Oakworth approach", "Oakworth methodology", "Oakworth process", "Oakworth framework", "Oakworth standards", 
    "Oakworth best practices", "Oakworth excellence", "Oakworth quality", "Oakworth precision", "Oakworth accuracy", 
    "Oakworth reliability", "Oakworth trust", "Oakworth confidentiality", "Oakworth security", "Oakworth discretion", 
    "Oakworth integrity", "Oakworth professionalism", "Oakworth experience", "Oakworth knowledge", "Oakworth insight", 
    "Oakworth wisdom", "Oakworth understanding", "Oakworth competence", "Oakworth capability", "Oakworth skill", 
    "Oakworth talent", "Oakworth leadership", "Oakworth innovation", "Oakworth excellence", "Oakworth results", 
    "Oakworth success", "Oakworth performance", "Oakworth achievement", "Oakworth growth", "Oakworth development", 
    "Oakworth improvement", "Oakworth enhancement", "Oakworth optimization", "Oakworth efficiency", "Oakworth effectiveness", 
    "Oakworth impact", "Oakworth value", "Oakworth benefit", "Oakworth advantage", "Oakworth edge", 
    "Oakworth competitive advantage", "Oakworth differentiation", "Oakworth uniqueness", "Oakworth specialization", 
    "Oakworth focus", "Oakworth concentration", "Oakworth dedication", "Oakworth commitment", "Oakworth passion", 
    "Oakworth enthusiasm", "Oakworth drive", "Oakworth determination", "Oakworth persistence", "Oakworth resilience", 
    "Oakworth adaptability", "Oakworth flexibility", "Oakworth agility", "Oakworth responsiveness", "Oakworth customer service", 
    "Oakworth client service", "Oakworth client satisfaction", "Oakworth client success", "Oakworth client results", 
    "Oakworth client value", "Oakworth client benefit", "Oakworth client advantage", "Oakworth client relationship", 
    "Oakworth partnership", "Oakworth collaboration", "Oakworth cooperation", "Oakworth teamwork", "Oakworth communication", 
    "Oakworth transparency", "Oakworth clarity", "Oakworth simplicity", "Oakworth complexity", "Oakworth sophistication", 
    "Oakworth elegance", "Oakworth refinement", "Oakworth polish", "Oakworth finish", "Oakworth quality", 
    "Oakworth excellence", "Oakworth superiority", "Oakworth preeminence", "Oakworth distinction", "Oakworth prominence", 
    "Oakworth recognition", "Oakworth reputation", "Oakworth credibility", "Oakworth authority", "Oakworth expertise", 
    "Oakworth mastery", "Oakworth proficiency", "Oakworth excellence", "Oakworth perfection", "Oakworth flawlessness", 
    "Oakworth impeccability", "Oakworth precision", "Oakworth accuracy", "Oakworth exactness", "Oakworth meticulousness", 
    "Oakworth thoroughness", "Oakworth completeness", "Oakworth comprehensiveness", "Oakworth detail", 
    "Oakworth attention to detail", "Oakworth care", "Oakworth diligence", "Oakworth conscientiousness", 
    "Oakworth responsibility", "Oakworth accountability", "Oakworth reliability", "Oakworth dependability", 
    "Oakworth trustworthiness", "Oakworth honesty", "Oakworth integrity", "Oakworth ethics", "Oakworth principles", 
    "Oakworth values", "Oakworth standards", "Oakworth conduct", "Oakworth behavior", "Oakworth character", 
    "Oakworth reputation", "Oakworth standing", "Oakworth status", "Oakworth position", "Oakworth rank", 
    "Oakworth level", "Oakworth class", "Oakworth grade", "Oakworth quality", "Oakworth caliber", 
    "Oakworth standard", "Oakworth measure", "Oakworth benchmark", "Oakworth yardstick", "Oakworth criterion", 
    "Oakworth requirement", "Oakworth expectation", "Oakworth demand", "Oakworth need", "Oakworth desire", 
    "Oakworth want", "Oakworth preference", "Oakworth choice", "Oakworth selection", "Oakworth decision", 
    "Oakworth judgment", "Oakworth discernment", "Oakworth wisdom", "Oakworth insight", "Oakworth perception", 
    "Oakworth understanding", "Oakworth comprehension", "Oakworth grasp", "Oakworth awareness", "Oakworth consciousness", 
    "Oakworth knowledge", "Oakworth learning", "Oakworth education", "Oakworth training", "Oakworth experience", 
    "Oakworth practice", "Oakworth skill", "Oakworth ability", "Oakworth capacity", "Oakworth competence", 
    "Oakworth capability", "Oakworth power", "Oakworth strength", "Oakworth force", "Oakworth energy", 
    "Oakworth vigor", "Oakworth vitality", "Oakworth dynamism", "Oakworth momentum", "Oakworth drive", 
    "Oakworth motivation", "Oakworth inspiration", "Oakworth enthusiasm", "Oakworth passion", "Oakworth zeal", 
    "Oakworth fervor", "Oakworth ardor", "Oakworth fire", "Oakworth intensity", "Oakworth concentration", 
    "Oakworth focus", "Oakworth attention", "Oakworth dedication", "Oakworth commitment", "Oakworth loyalty", 
    "Oakworth devotion", "Oakworth fidelity", "Oakworth faithfulness", "Oakworth constancy", "Oakworth steadfastness", 
    "Oakworth perseverance", "Oakworth persistence", "Oakworth tenacity", "Oakworth determination", "Oakworth resolve", 
    "Oakworth decision", "Oakworth will", "Oakworth volition", "Oakworth intention", "Oakworth purpose", 
    "Oakworth aim", "Oakworth goal", "Oakworth objective", "Oakworth target", "Oakworth end", 
    "Oakworth result", "Oakworth outcome", "Oakworth consequence", "Oakworth effect", "Oakworth impact", 
    "Oakworth influence", "Oakworth impression", "Oakworth mark", "Oakworth trace", "Oakworth sign", 
    "Oakworth indication", "Oakworth evidence", "Oakworth proof", "Oakworth demonstration", "Oakworth illustration", 
    "Oakworth example", "Oakworth instance", "Oakworth case", "Oakworth situation", "Oakworth circumstance", 
    "Oakworth condition", "Oakworth state", "Oakworth status", "Oakworth position", "Oakworth location", 
    "Oakworth place", "Oakworth spot", "Oakworth point", "Oakworth juncture", "Oakworth moment", 
    "Oakworth time", "Oakworth period", "Oakworth phase", "Oakworth stage", "Oakworth step", 
    "Oakworth level", "Oakworth degree", "Oakworth extent", "Oakworth scope", "Oakworth range", 
    "Oakworth reach", "Oakworth compass", "Oakworth breadth", "Oakworth width", "Oakworth expanse", 
    "Oakworth stretch", "Oakworth spread", "Oakworth sweep", "Oakworth span", "Oakworth distance", 
    "Oakworth interval", "Oakworth gap", "Oakworth space", "Oakworth room", "Oakworth opportunity", 
    "Oakworth chance", "Oakworth possibility", "Oakworth potential", "Oakworth capacity", "Oakworth ability", 
    "Oakworth power", "Oakworth strength", "Oakworth force", "Oakworth energy", "Oakworth vigor", 
    "Oakworth vitality", "Oakworth life", "Oakworth spirit", "Oakworth soul", "Oakworth essence", 
    "Oakworth nature", "Oakworth character", "Oakworth quality", "Oakworth attribute", "Oakworth property", 
    "Oakworth feature", "Oakworth aspect", "Oakworth element", "Oakworth component", "Oakworth part", 
    "Oakworth piece", "Oakworth segment", "Oakworth section", "Oakworth division", "Oakworth portion", 
    "Oakworth fraction", "Oakworth bit", "Oakworth scrap", "Oakworth shred", "Oakworth fragment", 
    "Oakworth remnant", "Oakworth remainder", "Oakworth residue", "Oakworth vestige", "Oakworth trace", 
    "Oakworth hint", "Oakworth suggestion", "Oakworth indication", "Oakworth implication", "Oakworth inference", 
    "Oakworth deduction", "Oakworth conclusion", "Oakworth judgment", "Oakworth decision", "Oakworth determination", 
    "Oakworth resolution", "Oakworth verdict", "Oakworth ruling", "Oakworth finding", "Oakworth discovery", 
    "Oakworth revelation", "Oakworth disclosure", "Oakworth exposure", "Oakworth unveiling", "Oakworth manifestation", 
    "Oakworth expression", "Oakworth display", "Oakworth show", "Oakworth demonstration", "Oakworth exhibition", 
    "Oakworth presentation", "Oakworth performance", "Oakworth execution", "Oakworth implementation", "Oakworth realization", 
    "Oakworth actualization", "Oakworth fulfillment", "Oakworth accomplishment", "Oakworth achievement", "Oakworth attainment", 
    "Oakworth realization", "Oakworth consummation", "Oakworth completion", "Oakworth finish", "Oakworth end", 
    "Oakworth termination", "Oakworth conclusion", "Oakworth close", "Oakworth cessation", "Oakworth stop", 
    "Oakworth halt", "Oakworth pause", "Oakworth break", "Oakworth rest", "Oakworth respite", 
    "Oakworth relief", "Oakworth ease", "Oakworth comfort", "Oakworth solace", "Oakworth consolation", 
    "Oakworth encouragement", "Oakworth support", "Oakworth assistance", "Oakworth help", "Oakworth aid", 
    "Oakworth relief", "Oakworth remedy", "Oakworth cure", "Oakworth solution", "Oakworth answer", 
    "Oakworth response", "Oakworth reply", "Oakworth reaction", "Oakworth comeback", "Oakworth retort", 
    "Oakworth rejoinder", "Oakworth replication", "Oakworth counter", "Oakworth return", "Oakworth payback", 
    "Oakworth repayment", "Oakworth reimbursement", "Oakworth compensation", "Oakworth recompense", "Oakworth reward", 
    "Oakworth prize", "Oakworth award", "Oakworth honor", "Oakworth recognition", "Oakworth acclaim", 
    "Oakworth praise", "Oakworth commendation", "Oakworth approval", "Oakworth endorsement", "Oakworth support", 
    "Oakworth backing", "Oakworth advocacy", "Oakworth promotion", "Oakworth advancement", "Oakworth furtherance", 
    "Oakworth progress", "Oakworth development", "Oakworth growth", "Oakworth expansion", "Oakworth extension", 
    "Oakworth enlargement", "Oakworth increase", "Oakworth rise", "Oakworth boost", "Oakworth surge", 
    "Oakworth jump", "Oakworth leap", "Oakworth bound", "Oakworth stride", "Oakworth step", 
    "Oakworth move", "Oakworth advance", "Oakworth headway", "Oakworth improvement", "Oakworth enhancement", 
    "Oakworth betterment", "Oakworth amelioration", "Oakworth refinement", "Oakworth perfection", "Oakworth optimization", 
    "Oakworth efficiency", "Oakworth effectiveness", "Oakworth productivity", "Oakworth performance", "Oakworth output", 
    "Oakworth yield", "Oakworth return", "Oakworth gain", "Oakworth profit", "Oakworth benefit", 
    "Oakworth advantage", "Oakworth value", "Oakworth worth", "Oakworth merit", "Oakworth excellence", 
    "Oakworth quality", "Oakworth superiority", "Oakworth preeminence", "Oakworth distinction", "Oakworth prominence", 
    "Oakworth importance", "Oakworth significance", "Oakworth weight", "Oakworth moment", "Oakworth consequence", 
    "Oakworth result", "Oakworth outcome", "Oakworth effect", "Oakworth impact", "Oakworth influence", 
    "Oakworth power", "Oakworth force", "Oakworth strength", "Oakworth might", "Oakworth muscle", 
    "Oakworth vigor", "Oakworth energy", "Oakworth vitality", "Oakworth life", "Oakworth spirit", 
    "Oakworth soul", "Oakworth essence", "Oakworth nature", "Oakworth character", "Oakworth quality", 
    "Oakworth attribute", "Oakworth property", "Oakworth feature", "Oakworth aspect", "Oakworth element", 
    "Oakworth component", "Oakworth part", "Oakworth piece", "Oakworth segment", "Oakworth section", 
    "Oakworth division", "Oakworth portion", "Oakworth fraction", "Oakworth bit", "Oakworth scrap", 
    "Oakworth shred", "Oakworth fragment", "Oakworth remnant", "Oakworth remainder", "Oakworth residue", 
    "Oakworth vestige", "Oakworth trace", "Oakworth hint", "Oakworth suggestion", "Oakworth indication", 
    "Oakworth implication", "Oakworth inference", "Oakworth deduction", "Oakworth conclusion", "Oakworth judgment", 
    "Oakworth decision", "Oakworth determination", "Oakworth resolution", "Oakworth verdict", "Oakworth ruling", 
    "Oakworth finding", "Oakworth discovery", "Oakworth revelation", "Oakworth disclosure", "Oakworth exposure", 
    "Oakworth unveiling", "Oakworth manifestation", "Oakworth expression", "Oakworth display", "Oakworth show", 
    "Oakworth demonstration", "Oakworth exhibition", "Oakworth presentation", "Oakworth performance", "Oakworth execution", 
    "Oakworth implementation", "Oakworth realization", "Oakworth actualization", "Oakworth fulfillment", "Oakworth accomplishment", 
    "Oakworth achievement", "Oakworth attainment", "Oakworth realization", "Oakworth consummation", "Oakworth completion", 
    "Oakworth finish", "Oakworth end", "Oakworth termination", "Oakworth conclusion", "Oakworth close", 
    "Oakworth cessation", "Oakworth stop", "Oakworth halt", "Oakworth pause", "Oakworth break", 
    "Oakworth rest", "Oakworth respite", "Oakworth relief", "Oakworth ease", "Oakworth comfort", 
    "Oakworth solace", "Oakworth consolation", "Oakworth encouragement", "Oakworth support", "Oakworth assistance", 
    "Oakworth help", "Oakworth aid", "Oakworth relief", "Oakworth remedy", "Oakworth cure", 
    "Oakworth solution", "Oakworth answer", "Oakworth response", "Oakworth reply", "Oakworth reaction", 
    "Oakworth comeback", "Oakworth retort", "Oakworth rejoinder", "Oakworth replication", "Oakworth counter", 
    "Oakworth return", "Oakworth payback", "Oakworth repayment", "Oakworth reimbursement", "Oakworth compensation", 
    "Oakworth recompense", "Oakworth reward", "Oakworth prize", "Oakworth award", "Oakworth honor", 
    "Oakworth recognition", "Oakworth acclaim", "Oakworth praise", "Oakworth commendation", "Oakworth approval", 
    "Oakworth endorsement", "Oakworth support", "Oakworth backing", "Oakworth advocacy", "Oakworth promotion", 
    "Oakworth advancement", "Oakworth furtherance", "Oakworth progress", "Oakworth development", "Oakworth growth", 
    "Oakworth expansion", "Oakworth extension", "Oakworth enlargement", "Oakworth increase", "Oakworth rise", 
    "Oakworth boost", "Oakworth surge", "Oakworth jump", "Oakworth leap", "Oakworth bound", 
    "Oakworth stride", "Oakworth step", "Oakworth move", "Oakworth advance", "Oakworth headway", 
    "Oakworth improvement", "Oakworth enhancement", "Oakworth betterment", "Oakworth amelioration", "Oakworth refinement", 
    "Oakworth perfection", "Oakworth optimization", "Oakworth efficiency", "Oakworth effectiveness", "Oakworth productivity", 
    "Oakworth performance", "Oakworth output", "Oakworth yield", "Oakworth return", "Oakworth gain", 
    "Oakworth profit", "Oakworth benefit", "Oakworth advantage", "Oakworth value", "Oakworth worth", 
    "Oakworth merit", "Oakworth excellence", "Oakworth quality", "Oakworth superiority", "Oakworth preeminence", 
    "Oakworth distinction", "Oakworth prominence", "Oakworth importance", "Oakworth significance", "Oakworth weight", 
    "Oakworth moment", "Oakworth consequence", "Oakworth result", "Oakworth outcome", "Oakworth effect", 
    "Oakworth impact", "Oakworth influence"
  ].join(", "),
  authors: [{ name: "The Oakworth Group" }],
  creator: "The Oakworth Group",
  publisher: "The Oakworth Group",
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: "https://theoakworth.com",
  },
  openGraph: {
    title: "The Oakworth Group | Financial Modeling & Private Equity Advisory",
    description: "Expert financial modeling, LBO analysis, debt structuring, and investment advisory services for private equity firms and corporations.",
    url: "https://theoakworth.com",
    siteName: "The Oakworth Group",
    images: [
      {
        url: "https://theoakworth.com/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "The Oakworth Group - Financial Modeling Experts",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "The Oakworth Group | Financial Modeling & Private Equity Advisory",
    description: "Expert financial modeling, LBO analysis, debt structuring, and investment advisory services for private equity firms and corporations.",
    images: ["https://theoakworth.com/twitter-image.jpg"],
    creator: "@theoakworth",
  },
  verification: {
    google: "your-google-verification-code",
    yandex: "your-yandex-verification-code",
  },
};